version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    labels:
      author.name: "Prateek Chhikara"
      author.email: "prateekchhikara24@gmail.com"
